### ISSUE TITLE
CalSpas 407T and CS6215R1A

### ISSUE THREAD

**Issue by smitterer** [olivierhill/Spaduino#2]
Hi!

I see this repository wasn't updated for a pretty long time but also the controller is pretty old, so might not be a problem.

Do you know if this would work with CalSpas 407T and CS6215R1A?

BTW, the link to http://www.olivierhill.ca/archives/74-Cal-Spa-Connector.html doesn't work.

Thanks!

**Comment by olivierhill** [comment]
I do not own the spa anymore, the controller looks similar to what I had with an 8 pin plug, but I cannot make any guarantee, this is just code I used in the past, YMMV

**Comment by smitterer** [comment]
Thanks for your feedback.
Did yours just have the 8 pin plug (Molex) and still use the RJ45 or did you go via the 8 pin plug?

How did you then connect to the atmega? Via an esp?

Thanks!
