### ISSUE TITLE
RJ45 or 8 Pin Molex

### ISSUE THREAD

**Issue by smitterer** [olivierhill/Spaduino#3]
Hi!

Did you use the RJ45 or a Molex-Connector?

Would you be able to republish https://www.olivierhill.ca/archives/74-Cal-Spa-Connector.html / make it public again?

Thanks!

**Comment by olivierhill** [comment]
Please understand this is a bug tracker and not a support forum. You can send PRs and the code is provided as-is according to the attached license.

You can thank AI for the destruction of web pages, I do not have archives.
